language: python
dist: bionic
python: "3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install verilator libevent-dev libjson-c-dev

install:
  # Get Migen / LiteX / Cores
  - cd ~/
  - wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
  - python3 litex_setup.py init install
  # Install the version being tested
  - cd $TRAVIS_BUILD_DIR
  - python3 setup.py install

before_script:
  # Get RISC-V toolchain
  - wget https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-20171231-x86_64-linux-centos6.tar.gz
  - tar -xvf riscv64-unknown-elf-gcc-20171231-x86_64-linux-centos6.tar.gz
  - export PATH=$PATH:$PWD/riscv64-unknown-elf-gcc-20171231-x86_64-linux-centos6/bin/

jobs:
  include:
    - stage: "Unit tests"
      script:
        - cd $TRAVIS_BUILD_DIR
        - python setup.py test
